kind: Pod
apiVersion: v1
metadata:
  name: myapp-readiness-probe
spec:
  conatiners:
    - name: goserver
      image: web:1.0
      ports:
        - containerPort: 80
  readinessProbe:
    httpGet:
      path: /healthz
      port: 80
    periodSeconds: 5
    initialDelaySeconds: 5
